# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
  task:
    scheduling:
      pool:
        size: 3 # scheduler定时器的线程数，缺省为1

---
# 开发环境配置


---
spring:
  config:
    activate:
      on-profile:


---
spring:
  config:
    activate:
      on-profile:
